# Site settings
title: Addisu's Log Book
email: 
permalink: /blog/:title/
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://addisu.taddese.com" # the base hostname & protocol for your site
url: "http://azeey.github.io" # the base hostname & protocol for your site
twitter_username: azeey
github_username:  azeey

# Build settings
markdown: kramdown

kramdown:
    input: GFM
    hard_wrap: false


google_analytics_key : UA-952444-7
gems: [jekyll-feed, jekyll-paginate, jekyll-redirect-from] # include feed plugin (supported by gh-pages)
